name: Version de Python

on:
  push:
    branches:
      - main

jobs:
  version_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10"]
    name: "Python version ${{ matrix.version }}"
    steps:
      - name: "Setup Python ${{ matrix.version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: "Afficher la version de Python"
        run: python --version
